version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Assumes package.json is in the root directory
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
